experiment:
  name: VisDrone2023ZeroShot
  group: cppe5
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  logger: clearml
  tracking_dir: experiments
  entity: null
  excluded_files: "*.pth"
  search: grid # search method to use (optim or grid)
  direction: max # direction of the search (max or min)
  n_trials: 40 # number of trials to run

parameters:
  tags: [[]]
  # train, test, inference
  phases: [[train, test]]
  print_model_summary: [False]
  dataset_interface: [vdzh/data/cppe5/CPPE5DatasetInterface]

  train_params:
    max_epochs: [1000]
    initial_lr: [0.00001, 0.01]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [vdzh/loss/ObjLoss]
      params:
        num_classes: &num_classes [5]
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [True]
    metric_to_watch: [f1]
    early_stopping_patience: [50]
    freeze_pretrained: [False]

  model:
    name: [vdzh/models/owlvit/OwlViT]
    params:
      pretrained: [True]

  dataset:
    channels: [["R", "G", "B"]]
    num_classes: *num_classes
    batch_size: [2]
    val_batch_size: [2]
    test_batch_size: [2]
  
  train_metrics:
    f1: &metric_params
      num_classes: *num_classes
  test_metrics:
    conf_mat: *metric_params
    f1: *metric_params
    precision: *metric_params
    recall: *metric_params
    jaccard: *metric_params

other_grids:
